baseURL: https://omango.org
languageCode: en-gb
defaultContentLanguage: en
title: Omango
theme: cupper-hugo-theme
# googleAnalytics: UA-123456789-1
# disqusShortname: yourdiscussshortname
# enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  # description: OmanGo is a group for people who know, use, or are just interested in starting to program in Go, the programming language designed and built at Google.
  # homeMetaContent: OmanGo is a group for people who know, use, or are just interested in starting to program in Go, the programming language designed and built at Google.
  footer: Created by [Hussein Al Abry](https://zidhuss.tech). Powered by [Hugo](https://gohugo.io/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  # codePenUser: someUser
  # katex: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Meetups
      url: /meetups/
      weight: 3
    # - name: Tags
    #   url: /tags/
    #   weight: 3
    # - name: RSS
    #   url: /index.xml
    #   weight: 5
