baseUrl: "/"
languageCode: en-gb
defaultContentLanguage: en
title: Omango
theme: cupper-hugo-theme
enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  footer: Created by [Hussein Al Abry](https://zidhuss.tech). Powered by [Hugo](https://gohugo.io/).
  dateFormat: Jan 2, 2006

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Meetups
      url: /meetups/
      weight: 3
